### ISSUE TITLE
problems with confirmation email creating account

### ISSUE THREAD

**Issue by camilozk** [processing/processing-forum#11]
hi

I created my account to participate in the forum, and I never received the confirmation email. I tried it several times with no results. several times

what to do?

**Comment by REAS** [comment]
I continue to receive email from people who don't receive the confirmation. I'll send over a recent one to you via email.

**Comment by fjenett** [comment]
Ok. I will have a look

**Comment by tillnagel** [comment]
Got another one who says they cannot register. (Wants to post re Unfolding.) Their e-mail address ends with @student.unimelb.edu.au

I just tried it with another e-mail address, and for me it worked.

**Comment by lriq** [comment]
Hi, I'm having the same problem. I've tried several times, and I haven't received anything. What should I do? Thanks!

**Comment by REAS** [comment]
@Iriq Give us a piece of your email address (I have one from Till) and we can manually approve it.

**Comment by lriq** [comment]
Hi, my email address is linda_riquelme@hotmail.com.  Thanks!




-------- Original message --------

**Comment by REAS** [comment]
@tillnagel I need the full email for the search. Please give me that first part here or by email.

**Comment by tillnagel** [comment]
@REAS Meanwhile they informed me they used a different e-mail address. Sorry for the noise.

**Comment by fjenett** [comment]
I just did take a look at our registration filtering mechanism and i think i have a candidate for the problems. Will need some time to find a way to debug this further.

Sorry for the inconvenience caused!

**Comment by maxarch** [comment]
hello i have same problem. i register with 3 e-mail and nothing came back.

**Comment by fjenett** [comment]
@maxarch … please send me an email to mail-at-bezier-dot-de with the addresses, so i can check

**Comment by maxarch** [comment]
ok thanks i have send you a e-mail

**Comment by Lena-M** [comment]
I received the confirmation mail, but my E-Mail address could not be confirmed.
I hope someone can help?
Thanks, Lena

**Comment by fjenett** [comment]
What means "could not be confirmed"? … can you send me (mail-at-bezier-dot-de) your email address?

**Comment by fjenett** [comment]
After registration you can request another email confirmation mail through this link:
https://forum.processing.org/two/entry/emailconfirmrequest

… in case the original one got lost.

**Comment by dedsresende** [comment]
Hi I created an acount on processing forum but I tried several times and I just don't receive my confirmation e-mail, what should I do?

**Comment by hjesper** [comment]
Hi, I am not receiving my confirmation email. I tried with my hotmail and gmail address.
jespernoerbaek-at-gmail-dot-com

**Comment by fjenett** [comment]
@dedsresende what is the email address you used to sign up?

**Comment by dedsresende** [comment]
@fjenett dedsresende@gmail.com.
Thank you very much!

**Comment by fjenett** [comment]
Should work now … try again

**Comment by hjesper** [comment]
Works now thank you :)

**Comment by dedsresende** [comment]
not yet...

**Comment by dedsresende** [comment]
Working! Thank you very much @fjenett

**Comment by Phonicz** [comment]
Help please, I need help with my code but the confirmation email for the processing forums wont send.

email:
r3zoar@gmail.com

username on forum:
Phonicz

**Comment by dagauchman** [comment]
I have also not received a confirmation email.

email:
davidmgauch@gmail.com

username on forum:
Dave_Gauch

**Comment by chrisjmendoza** [comment]
Same here.

email:
chrisjmendoza@gmail.com

username:
chrismendoza

**Comment by Arseniusz** [comment]
Hello. I have also not received an email/

prosvirnin.arseniy@gmail.com

**Comment by fjenett** [comment]
@chrisjmendoza, @dagauchman, @Arseniusz, @Phonicz … you should all be set now. Try again please.

**Comment by fjenett** [comment]
Note to all: please don't post your email address here. Send me a direkt message through the forum (fjen) or email me …

**Comment by Phonicz** [comment]
Will do in the future, Thanks for the help.

**Comment by chrisjmendoza** [comment]
Thank you!!!! I couldn't figure out how to send a direct message lol

**Comment by FrankOcean11** [comment]
im having the same issues

**Comment by couleurs** [comment]
Same issues. Just sent you an email @fjenett . Thanks!

**Comment by malaschitz** [comment]
the same

**Comment by fjenett** [comment]
**Please email me if you have trouble signing up.**

**Comment by macmailservice** [comment]
I received the confirmation mail, but my E-Mail address could not be confirmed.
I hope someone helps me.
[https://babasupport.org/apple/mac-mail-customer-service/258](url)

**Comment by arunavanag591** [comment]
@fjenett what is your email? I am having the same issue.
