### ISSUE TITLE
Forum redirect not working over HTTPS

### ISSUE THREAD

**Issue by javl** [processing/processing-forum#12]
I'm using the EFF's 'HTTPS Everywhere' browser extension, which forces your browser to always favor a HTTPS connection over a HTTP one (if available). With the plugin enabled, I'm not able to visit the forums because https://forum.processing.org does exist (and so is used by the extension) but it does not redirect me to the forum - it just shows the Processing homepage. I need to visit http://forum.processing.org instead.

Though it's the extension that forces me to use the HTTPS page (when I disable it I can just visit the HTTP address), I think the page not redirecting is still an error on the Processing server (the HTTPS page does exist, but it not working properly).

**Comment by Jed-SWSDT** [comment]
Concur. Ran into the same problem and at first assumed that Processing had undergone yet another forum change.

**Comment by fjenett** [comment]
Should be fixed now
