### ISSUE TITLE
Could not pose a question in Forum

### ISSUE THREAD

**Issue by ertorque** [processing/processing-forum#13]
Hi, I managed to sign up to be a member of the forum but upon signining in all I could do is view questions and comments. I could not see anything I could click on to pose a question. Any help is appreciated. Thanks!

![image](https://cloud.githubusercontent.com/assets/15143973/10531865/a9e18ef6-73e9-11e5-8b38-620237689cf6.png)

**Comment by fjenett** [comment]
Please send me (mail-at-bezier-dot-de) the email-address you used to sign up … we had trouble sending emails through the forum and your confirmation email might have gotten lost.

Or even better, click this link to have the confirmation email being resent to you:
https://forum.processing.org/two/entry/emailconfirmrequest

**Comment by ertorque** [comment]
Hi Florian,

Clicking on the link you sent yielded the message " Your email needs no
confirmaton". The email I used to sign up is ertorque@gmail.com.
Your suppport is most appreciated.


WIth regards
CY Fong

**Comment by ertorque** [comment]
Hi Florian,

I am still unable to pose a question even though I am signed in. I just couldn't see the "Ask a question" button.
Thanks.

CY Fong

**Comment by FrankOcean11** [comment]
im having the same issue!

**Comment by fjenett** [comment]
@ertorque @FrankOcean11 … both of you should be able to post now.

Note to all: please email me instead of posting here about registration problems …

**Comment by FrankOcean11** [comment]
Thanks i got that ask icon.....

**Comment by ertorque** [comment]
Thanks fjenett, i got that icon too.
