### ISSUE TITLE
Got problem with posting in processing forum.

### ISSUE THREAD

**Issue by Darius135** [processing/processing-forum#15]
Hello pro brothers,
Please help. I want to post on processing forum.But, there is no option to post. I got a problem to create a game and stucked and having problem. Please help. 
Thank you.

**Comment by fjenett** [comment]
What is the user name that you registered as?

**Comment by Darius135** [comment]
Darius135.. Same as this name. :)

**Comment by fjenett** [comment]
Fixed. Try now …

**Comment by Darius135** [comment]
Woaaaa... Bro,thank you... :) +1:
