### ISSUE TITLE
Cannot sign up to processing-forum

### ISSUE THREAD

**Issue by jcdutton** [processing/processing-forum#18]
Hi,

I try to sign up to processing forum.
It sent me an email which has a "confirm you email" link.
I clicked on it, but got this:
"We couldn't confirm your email. Check the link in the email we sent you or try sending another confirmation email."
When I try to click on the "To send another confirmation email click here." I get:
"Your email doesn't need confirmation."

I cannot comment or open new discussion threads.

I wish to highlight how to get processing P2D/P3D working with xvfb.
Problems with Processing  P2D Xvfb
I had problem getting it working, I got just a black screen as output.
The solution is to use "noSmooth()"  after the size(...) 
public void settings() {
                size(800, 600, P2D);
                noSmooth();
        }

Xvfb does not do multisampling, so does not like the attribute list parameters  
//                GLX_SAMPLE_BUFFERS, 1,
//                GLX_SAMPLES, 2,
By setting noSmooth(), it does not request GLX_SAMPLES, 2 any more, and therefore works with Xvfb.

**Comment by kfrajer** [comment]
Are you referring to this [post](https://forum.processing.org/two/discussion/comment/94734/#Comment_94734)? 

kfrajer

**Comment by jcdutton** [comment]
Yes. using "nosmooth()  will fix their issue.

**Comment by fjenett** [comment]
We are moving on to a new forum software, try here: https://discourse.processing.org/
