### ISSUE TITLE
Edit discussion error response about XML parsing

### ISSUE THREAD

**Issue by fjenett** [processing/processing-forum#2]
![screen shot 2014-03-27 at 10 02 49 am](https://cloud.githubusercontent.com/assets/59608/2642574/2028dac8-bf0b-11e3-9553-ab6d70b08598.png)
![screen shot 2014-03-27 at 10 03 17 am](https://cloud.githubusercontent.com/assets/59608/2642575/202ac8d8-bf0b-11e3-8985-00ed70511c8f.png)

**Comment by fjenett** [comment]
The problem is the response time of the spam servers i guess … we send information there and if that takes too long the script does time out (i guess).

From your experience is this still a problem with the new forum version as well?

**Comment by PhiLhoSoft** [comment]
I haven't seen this message for a long time, now.

**Comment by fjenett** [comment]
Oh great!

**Comment by PhiLhoSoft** [comment]
Oops, looks like I spoke too fast!
Today, I am getting this error message again...
`{"Code":0,"Exception":"String could not be parsed as XML","Class":"Exception"}`

**Comment by fjenett** [comment]
Meeeh. OK, thanks
