### ISSUE TITLE
Bug in my code

### ISSUE THREAD

**Issue by ryanfelner** [processing/processing-forum#20]
I am trying to create an algorithm that finds all integers up to a certain maximum number such that the sum of all its digits is a factor of the number itself. To isolate the digits in each number I've been converting the integer to a String, taking each digit and converting it back into an integer, and adding them together. For some reason, my code does not work. Any advice?

```
ArrayList <Integer> numbers = new ArrayList <Integer>();

void setup() {
  factor(100);
  println(numbers);
}

void factor(int max) {
  for (int i = 1; i < max; i++) {
    if (digits(i)) {
      numbers.add(i);
    }
  }
}

boolean digits (int number) {
  String numbers = nf(number);
  int[] digits = new int[numbers.length()];

  for (int i = 0; i < digits.length; i++) {
    digits[i] = int(numbers.charAt(i));
  }

  int sum = 0;

  for (int i = 0; i < digits.length; i++) {
    sum += digits[i];
  }

  if (number % sum == 0) {
    return true;
  } else {
    return false;
  }
}
```

**Comment by REAS** [comment]
We just GitHub to work on developing the software. The Processing Forum is the spot for asking questions about a program: https://forum.processing.org
