### ISSUE TITLE
Random color and moving object

### ISSUE THREAD

**Issue by Noobprogrammer73** [processing/processing-forum#21]
I have to make a race with Robots. 
With a slider i can choose the amount of Robots I want to race.
So i made a method to draw a Triangle(supposed to be a robot)
I did the method in a for loop. So it draws the amount of triangles i want.
But i want to give it a random color and then let it keep the color.
Now the triangles are made of flickering colors.
I am stuck on this for a long time now.

**Comment by REAS** [comment]
Please post this on the forum: https://forum.processing.org
