### ISSUE TITLE
Idea: remind users how to ask good questions

### ISSUE THREAD

**Issue by hamoid** [processing/processing-forum#23]
Hi! I see many questions in the forum which do not provide enough information to be able to help. Something like "X is not working. I tried many things. What can I do?". So the first step would be to write back and ask for those details that should have been there in the first place.

I think it might help to include a text above the form in the forum explaining in a few words how to ask good questions to get an answer faster (tell what you did, what you got, what you expected, what are you trying to do, show code, maybe include OS and P5 version, etc). Or even link to something like https://stackoverflow.com/help/mcve

This is how it looks currently:

![2018-02-23-152554_1008x644_scrot](https://user-images.githubusercontent.com/108264/36599294-3e5a1988-18af-11e8-9e8a-7741a4e91f10.png)

Maybe a "tips for getting help faster: xxxxxx"?

**Comment by fjenett** [comment]
New forum here: https://discourse.processing.org/

**Comment by hamoid** [comment]
Happy to see it live! The new forum does help with guiding users to make better questions from a "social" point of view, but I didn't see tips on how to make better "software" questions. There's a faq, but it mentions things about being nice to others and such. Should that FAQ be edited, or the question dialog tweaked, to let people know how to ask better questions in the Processing context? (show the error, indicate which version you are using, your OS, etc)
