### ISSUE TITLE
Broken redirect at bottom log in link in post

### ISSUE THREAD

**Issue by hamoid** [processing/processing-forum#24]
If you are in a post, say

https://forum.processing.org/two/discussion/26489/minim-audio-loop-infinite

and log in using the link under the post, which looks like this:

https://forum.processing.org/two/entry/signin?Target=%2Ftwo%2Fdiscussion%2F26489%2Fminim-audio-loop-infinite

once logged in it takes you to a 404 page (notice the **two/two**)

https://forum.processing.org/two/two/discussion/26489/minim-audio-loop-infinite

**Comment by fjenett** [comment]
We are moving on to a new forum, find it here: https://discourse.processing.org/
