### ISSUE TITLE
Adding MP3 in processing (TUIO)

### ISSUE THREAD

**Issue by Agirll** [processing/processing-forum#25]
Hi!,
Just getting started on using processing with TUIO. All I basically want to do is place a fiducial marker in front of the camera and then trigger a mp3 file. I have everything set up and the markers are being tracked by the camera. Now i just want it to trigger audio too. I haven't come across anything. Can someone kindly point me in the right direction? or does anyone have some examples?
Thanks you & kind regards

**Comment by fjenett** [comment]
Please ask here: https://discourse.processing.org/
