### ISSUE TITLE
Please allow people to mark replies to their own own questions as the accepted answer

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing-forum#5]
Example: I asked on the forum why the RSS feed no longer works:

http://forum.processing.org/two/discussion/4423/what-happened-to-the-rss-feed-of-processing-org

... then replied to the conversation that I opened a ticket about it on Github:

https://github.com/processing/processing-web/issues/388

... where I was promptly given an explanation for my question. So the most sensible thing to do would be to mark my own reply as an answer to my question. I can think of more situations where this applies: a "Hey guys how do I...." followed by a "Nevermind, [writing out that question helped me answer it](https://en.wikipedia.org/wiki/Rubber_duck_debugging), here's my solution" for example.

**Comment by fjenett** [comment]
Hey, moving on to a new forum: https://discourse.processing.org/
