### ISSUE TITLE
Block comments spread through code

### ISSUE THREAD

**Issue by PhiLhoSoft** [processing/processing-forum#9]
It is an old bug, I finally took the time to investigate. Block comments tend to spread through the code, although doc. comments doesn't.

In http://forum.processing.org/two/plugins/G_SyntaxHighlighter/scripts/shBrushProcessing20.js there are regular expressions to match various parts of the code.

The one for block comments is: `/\/\*([^\*][\s\S]*)?\*\//gm`
It is missing a non-greedy quantifier: `/\/\*([^\*][\s\S]*?)?\*\//gm`
<strike>Can probably be simplified, since we use the `m` modifier: `/\/\*(?:[^*].*?)?\*\//gm`</strike>
<strike>For doc. comments: `/\/\*(?!\*\/)\*.*?\*\//gm`</strike>
<strike>Cleaner / easier to understand than the [\s\S] hack (clever, but puzzling at first).</strike>

Untested yet, I must see if I can make a Greasemonkey script to test it, somehow.

**Comment by fjenett** [comment]
Did you get to test this?

**Comment by PhiLhoSoft** [comment]
No, Greasemonkey is too late in the game, the original JS will be already loaded when it kicks in. The other solutions involves using some proxy to intercept the JS file and replace it with another. I didn't found time to try this.

Would it be problematic to try the fix on the live forum, and revert it if not working?

**Comment by fjenett** [comment]
We are moving on to a new forum: https://discourse.processing.org/
